# Generated by Django 5.0.3 on 2024-05-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
